apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: spring-training
data:
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=
  POSTGRES_PASSWORD: c3ByaW5nLXRyYWluaW5n
  POSTGRES_USER: c3ByaW5nLXRyYWluaW5nX3VzZXI=
type: Opaque