apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: spring-training
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP