apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: spring-training
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP