apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: spring-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:5.0
          ports:
            - containerPort: 9000
            - containerPort: 12201
          envFrom:
            - secretRef:
                name: graylog-secrets
      restartPolicy: Always