apiVersion: v1
kind: Service
metadata:
  name: graylog-service
  namespace: spring-training
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: graylog
  type: ClusterIP